Repository CZERTAINLY/CZERTAINLY-Appliance-Tools, pull requests merged in 2023-06, with the labels that each got.

#13 how to recognize changed role files
  README.md
Labels: documentation

#17 fix handling errors when publishing builded package
  .github/workflows/build-deb.yml
  debian/changelog
Labels: bug

#16 fix output when namespace is missing
  usr/bin/czertainly-status
Labels: bug

#20 allow user to only install CZERTAINLY
  debian/changelog
  etc/sudoers.d/czertainly
  usr/bin/czertainly-tui
Labels: enhancement

#23 kill only space on beiging and end of line
  usr/bin/czertainly-tui
Labels: bug

#25 fix 2.6.0
  debian/changelog
Labels: bug

#26 release version 2.7.1
  debian/changelog
Labels: enhancement

#27 Master to Develop Merge
  .github/workflows/build-deb.yml
  debian/changelog
Labels: documentation

#29 prepare 2.8.0 release
  debian/changelog
  etc/czertainly-ansible/vars/czertainly.yml
Labels: enhancement
